db: update to fix rpmbuild
The rpmbuild (by CPack) was failing while packing the python script
db/tools/postgresql.py as:

+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip
/usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
error: Bad exit status from /var/tmp/rpm-tmp.GcKAGE (%install)
	    Bad exit status from /var/tmp/rpm-tmp.GcKAGE (%install)

complaining about the print(..., flush = True). This issue is now fixed.

Signed-off-by: Jan Viktorin <iviktorin@fit.vutbr.cz>